#!/bin/sh

set -euC

cd "$(dirname "$(readlink -f "$0")")"

if [ $# -eq 0 ]; then
    >&2 echo 'Version must be provided as first argument'
    exit 1
fi

confirm() {
    read -p "{$1:-Continue?} (Y/N): " confirm

    case "$confirm" in
    [yY][eE][sS]|[yY])
        # Continue
        ;;
    [nN][oO]|[nN])
        exit 1
        ;;
    *)
        echo "Invalid response. Aborting..."
        exit 2
        ;;
    esac
}

version=$1; shift

if [ -z "$version" ]; then
    >&2 echo 'Invalid version value'
    exit 1
fi

# TODO: Can't be dirty!

git tag "v${version}" || [ "$(git name-rev --name-only --tags HEAD)" = "v${version}" ]

export ORG_GRADLE_PROJECT_pluginReleaseVersion="$version"

#./gradlew clean
./gradlew buildPlugin

cp -a build/distributions/php_declaration_hints-intellij-plugin{,-v${version}}.zip

./gradlew runIde

confirm "Push commits and tag 'v${version}' to GitHub?"
git push github
git push github "v${version}"


if confirm "Tag 'v${version}' as 'latest' and push to GitHub?"; then
    git tag latest "v${version}"
    git push github latest
fi
